# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAKNqkuTah77MkFVkhXbzBvvs7cnFSln
"""

import matplotlib.pyplot as plt
import pandas as pd

# Data untuk grafik dan tabel
n = [5, 10, 15, 20, 25]  # Jumlah pemesanan
recursive_time = [0.00002598, 0.00004464, 0.00008062, 0.00264464, 0.82734895]  # Waktu rekursif (s)
iterative_time = [0.00000452, 0.00000405, 0.00000291, 0.00000657, 0.00000834]  # Waktu iteratif (s)

# Membuat DataFrame untuk tabel
data = {
    'n (Jumlah Pemesanan)': n,
    'Recursive Time (s)': recursive_time,
    'Iterative Time (s)': iterative_time
}
df = pd.DataFrame(data)

# Menampilkan tabel
table_output = df.to_markdown(index=False, tablefmt="grid")
print("Tabel Perbandingan Waktu Eksekusi:\n")
print(table_output)

# Membuat grafik
plt.figure(figsize=(10, 6))
plt.plot(n, recursive_time, marker='o', color='red', label='Recursive Time')
plt.plot(n, iterative_time, marker='o', color='blue', label='Iterative Time')

# label dan judul
plt.title("Perbandingan Waktu Eksekusi: Iteratif vs Rekursif", fontsize=14)
plt.xlabel("Jumlah Pemesanan (n)", fontsize=12)
plt.ylabel("Waktu Eksekusi (detik)", fontsize=12)
plt.yscale("log")  # Menggunakan skala logaritmik untuk memvisualisasikan perbedaan besar
plt.legend()
plt.grid(True, which="both", linestyle="--", linewidth=0.5)

# Tampilan grafik
plt.tight_layout()
plt.show()
